language: go
sudo: false
go:
  - 1.5
  - 1.6
  - 1.7
  # NOTE: Stop using tip to avoid the following error on Travis CI:
  # I don't have any idea what to do with 'tip'.
  # - tip
env:
  global:
    - GO15VENDOREXPERIMENT=1
    - TEST_TIMEOUT_SCALE=10
cache:
  directories:
    - vendor
install:
  - make dependencies
script:
  - make lint
  - make test
after_success:
  - make coveralls
