language: go
sudo: false
go:
  - 1.7
  - 1.8
go_import_path: github.com/hnakamur/zap-ltsv
env:
  global:
    - TEST_TIMEOUT_SCALE=10
cache:
  directories:
    - vendor
install:
  - go get -u ./...
script:
  - go test -v ./...
